version: "3.9"
services:
  valheim:
    image: ghcr.io/mts-gaming/valheim:latest
    cpus: 4
    mem_limit: 6144m
    restart: on-failure
    ports:
      - "2456:2456/udp"
      - "2456:2456/tcp"
      - "2457:2457/tcp"
    environment:
      VALHEIM_NAME: Valheim Online
      VALHEIM_PORT: 2456
      VALHEIM_PASSWORD: ThorOdinson
      VALHEIM_WORLD: valheim
      VALHEIM_PUBLIC: 1
    volumes:
      - valheim:/root/.config/unity3d/IronGate/Valheim

volumes:
  valheim: