name: Build and Publish
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"
      - "docker-compose.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.1.0
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ steps.string.outputs.lowercase }}:latest
          pull: true

      - name: Update Docker Compose
        run: sed -i "s#mts-gaming/valheim:[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]#mts-gaming/valheim:$(git rev-parse --short HEAD)#g" docker-compose.yml

      - name: GIT Commit Docker Compose
        run: |
          git config --global user.name "CI/CD"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "[CI/CD] Update"
          git push
