name: Update docker-compose
on:
  registry_package:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Docker Compose
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Docker Compose
        id: vars
        run: sed -i "s#mts-gaming/valheim:[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]#mts-gaming/valheim:$(git rev-parse --short HEAD)#g" docker-compose.yml

      - name: GIT Commit Docker Compose
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
